### ISSUE TITLE
Roadmap to construct this api

### ISSUE THREAD

**Issue by pauloestrella1994** [pauloestrella1994/work_at_olist#1]

**Comment by pauloestrella1994** [comment]
- [x] Create a repository in github;
- [x] Create a directory and clone the project;
- [x] Create a virtual enviroment;
- [x] Add a generic README and add folders and files in .gitignore;
- [x] Upgrade pip;
- [x] Install Django and djangorestframework;
- [x] Start project and apps with django-admin commands;
- [x] Configure settings, migrate and test runserver;
- [ ] Create models and apply migrations;
- [x] Create a super user;
- [ ] Populate data into the django admin forms;
- [ ] Create a Serializer;
- [ ] Create a Viewsets;
- [ ] Create  a list of urls;
- [ ] Test http verbs in insomnia or postman;
- [ ] Make tests with pytest to the api;
- [ ] Create a custom command to import authors;
- [ ] Make tests to the command;
- [ ] Runs tests;
- [ ] Generic review and fixings;
